"""empty message

Revision ID: a563540d5e06
Revises: 
Create Date: 2018-06-22 11:45:06.552623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a563540d5e06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blacklist', 'available')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist', sa.Column('available', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
