"""empty message

Revision ID: 9fdaae23ed66
Revises: 196e194ddf5b
Create Date: 2018-04-16 16:08:09.766740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fdaae23ed66'
down_revision = '196e194ddf5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('authorized', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=True))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('user', 'password')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'authorized')
    # ### end Alembic commands ###
